"""Auto migration

Revision ID: 007203dd1cb1
Revises: adc0bbdcd8c0
Create Date: 2024-05-24 16:26:06.951062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007203dd1cb1'
down_revision: Union[str, None] = 'adc0bbdcd8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
