"""Auto migration

Revision ID: 2d4fde8b6e22
Revises: d3e4e1fa975f
Create Date: 2024-05-24 15:37:36.918502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4fde8b6e22'
down_revision: Union[str, None] = 'd3e4e1fa975f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
