"""Auto migration

Revision ID: 7c013aa78d0f
Revises: a5bcfd0949e8
Create Date: 2024-05-26 03:15:44.786230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c013aa78d0f'
down_revision: Union[str, None] = 'a5bcfd0949e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
