"""Auto migration

Revision ID: d3e4e1fa975f
Revises: 7fc0f2a99aa1
Create Date: 2024-05-24 01:53:24.685939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd3e4e1fa975f'
down_revision: Union[str, None] = '7fc0f2a99aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admins_ibfk_1', 'admins', type_='foreignkey')
    op.create_foreign_key(None, 'admins', 'admin_roles', ['role_id'], ['id'])
    op.add_column('articles', sa.Column('author', sa.String(length=255), nullable=True))
    op.alter_column('categories', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('categories', 'display',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('categories', 'order',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint('order_items_ibfk_1', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_ibfk_2', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    op.drop_constraint('products_ibfk_1', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'membership_levels', ['membership_level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'membership_levels', ['membership_level_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_ibfk_1', 'products', 'categories', ['category_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_ibfk_2', 'order_items', 'products', ['product_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('order_items_ibfk_1', 'order_items', 'orders', ['order_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.alter_column('categories', 'order',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('categories', 'display',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('categories', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.drop_column('articles', 'author')
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.create_foreign_key('admins_ibfk_1', 'admins', 'admin_roles', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    # ### end Alembic commands ###
